const mongoose = require("mongoose");
const bcrypt = require("bcrypt");
require('dotenv').config();

const first = [
  "Jasmine",
  "Connor",
  "Sophia",
  "Elijah",
  "Olivia",
  "Xavier",
  "Mia",
  "Gabriel",
  "Isabella",
  "Liam",
  "Ava",
  "Noah",
  "Emma",
  "Lucas",
  "Charlotte",
  "Aiden",
  "Harper",
  "Ethan",
  "Amelia",
  "Mason",
  "Evelyn",
  "Logan",
  "Emily",
  "Owen",
  "Abigail",
  "Jackson",
  "Chloe",
  "Carter",
  "Grace",
  "Caleb",
  "Madison",
  "Henry",
  "Zoe",
  "Benjamin",
  "Lily",
  "Samuel",
  "Scarlett",
  "Alexander",
  "Riley",
  "Victoria",
  "Daniel",
  "Penelope",
  "Matthew",
  "Natalie",
  "Julian",
  "Audrey",
  "David",
  "Layla",
  "Christopher",
  "Stella",
];

const last = [
  "Patel",
  "Mitchell",
  "Nguyen",
  "Thompson",
  "Smith",
  "Rodriguez",
  "Johnson",
  "Brown",
  "Kim",
  "Jones",
  "Martinez",
  "White",
  "Garcia",
  "Lee",
  "Williams",
  "Jackson",
  "Davis",
  "Wilson",
  "Taylor",
  "Thomas",
  "Hernandez",
  "Robinson",
  "Clark",
  "Lewis",
  "Moore",
  "Walker",
  "Adams",
  "Turner",
  "Stewart",
  "King",
  "Baker",
  "Green",
  "Carter",
  "Hill",
  "Cooper",
  "Morales",
  "Hall",
  "Reed",
  "Rogers",
  "Foster",
  "Perry",
  "Brooks",
  "Ward",
  "Ramirez",
  "Coleman",
  "Long",
  "Price",
  "Richardson",
  "Barnes",
  "Murphy",
];

// Get a random item given an array
const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const makeUser = async (discipline) => {
    const salt = parseInt(process.env.SALT_ITERATION);
    const firstName =  getRandomArrItem(first);
    const lastName =  getRandomArrItem(last);
    const passwordHash = await bcrypt.hash('password1234', salt);
    const newUser = {
        _id: new mongoose.Types.ObjectId(),
        name: `${firstName} ${lastName}`,
        email: `${firstName}.${lastName}@gmail.com`,
        password: passwordHash,
        discipline: discipline,
    };
    return newUser;
}

module.exports = makeUser;